### ISSUE TITLE
Add helper function for BPMN moddle extensions

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler-plugin-helpers#1]
Once moddle extension plugins are possible in the Camunda Modeler this helper function should be added:

```javascript
function registerBpmnJSModdleExtension(plugin) {
  registerClientPlugin(plugin, 'bpmn.modeler.moddleExtension');
}
```

See https://github.com/camunda/camunda-modeler/pull/949.

**Comment by philippfromme** [comment]
@nikku I don't seem to have any permissions regarding this repository. I can't push my changes.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler-plugin-helpers/pull/3.
