### ISSUE TITLE
Create new plugin helpers to register C7 and C8 specific plugins

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda-modeler-plugin-helpers#20]
__Is your feature request related to a problem? Please describe.__

To abstract away the specific keys we will use to identify C7 and C8 plugins, and make life simpler for plugin developers, we should create new plugin registrations helper functions for:

- C7 bpmn
- C8 bpmn
- C7 moddle
- C8 moddle

__Describe the solution you'd like__

Keep the old registration methods for backward compatibility, create some new ones for allowing differentiation between C7 and C8 plugins.

__Describe alternatives you've considered__

Removing the old ones and proceeding with new ones, but this would break too many things and make plugin developers have to choose between supporting modeler 4 and 5

**Comment by nikku** [comment]
Could you add information on how your different issues / PRs depend on each other?

That makes it easier to track your progress / review in a reasonable order.

A simple note on the issue/pr gets the job done:

```
Depends on org/repo#issueNr
```

**Comment by Skaiir** [comment]
@nikku I try to do that when it makes sense. This here has no hard dependency on anything, but I guess the functions will not do much until the functionality to pick up the registrations is setup in modeler.

So this should be merged within relative proximity of https://github.com/camunda/camunda-modeler/issues/2777

**Comment by nikku** [comment]
What always helps me is to bring the things into total order.

Yes, both are interconnected, but which one does not make sense if the other one would not exist? Then I have an order in which I'd review it.

**Comment by Skaiir** [comment]
I would say this one comes second, because we expose the generic `registerClientPlugin` already here which can be used instead of the new helpers.

**Comment by Skaiir** [comment]
But if they were in the same repo I would only have one PR
