### ISSUE TITLE
Cut a new stable release

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler-plugin-helpers#5]
We're exposing a couple of new helpers/extension points with `camunda-modeler-plugin-helpers@next` and should consider making those available with a new stable release.

Before doing that we'd need to clarify a few things though:

* Right now we catch compatibility errors (Camunda Modeler versions < 3.4) with a `Camunda Modeler >= 3.4 required`. This is bad considering that plug-ins built using the helpers can be run in the Zeebe Modeler, too. 
* We need to decide how to structure these compatibility warnings. Looking into the future, what information should they provide? Should the editors expose their own names and current versions so we have some additional debug output that users can inspect for error handling?

**Comment by philippfromme** [comment]
> * Camunda Modeler >= 3.4 required

Where do we catch this?

**Comment by nikku** [comment]
> Where do we catch this?

Here: https://github.com/camunda/camunda-modeler-plugin-helpers/blob/master/react.js#L2

**Comment by philippfromme** [comment]
> Here: https://github.com/camunda/camunda-modeler-plugin-helpers/blob/master/react.js#L2

Ouch. 😄

**Comment by Skaiir** [comment]
Closed with release 5.0.0
